export interface ProjectFormValues {
  project_name: string;
  actual_capacity_kwp: string;
  simulation_capacity_kwp: string;
  total_bess_kwh: string;
  bess_power_rating_kw: string;
  dod: string;
  half_cycle_efficiency: string;
  bess_enabled: string;
  strategy_mode: string;
  charging_mode: string;
  charge_start_hour: string;
  charge_end_hour: string;
  min_direct_pv_share: string;
  active_pv2bess_share: string;
  precharge_target_soc_kwh: string;
  precharge_target_hour: string;
  dppa_enabled: string;
  strike_price_vnd: string;
  k_factor: string;
  connection_voltage_kv: string;
  kpp_22: string;
  kpp_110: string;
  tariff_off_peak: string;
  tariff_standard: string;
  tariff_peak: string;
  exchange_rate_usd_vnd: string;
  solar_usd_per_mwp: string;
  bess_usd_per_mwh: string;
  base_rate: string;
  debt_margin: string;
  tenor_years: string;
  target_dscr: string;
  project_years: string;
  financial_close_serial: string;
  cod_excel_serial: string;
  degradation_json: string;
}

export const defaultFormValues: ProjectFormValues = {
  project_name: "",
  actual_capacity_kwp: "3221",
  simulation_capacity_kwp: "100",
  total_bess_kwh: "2150",
  bess_power_rating_kw: "1000",
  dod: "0.85",
  half_cycle_efficiency: "0.95",
  bess_enabled: "true",
  strategy_mode: "1",
  charging_mode: "1",
  charge_start_hour: "10",
  charge_end_hour: "16",
  min_direct_pv_share: "0.1",
  active_pv2bess_share: "0.3",
  precharge_target_soc_kwh: "1500",
  precharge_target_hour: "17",
  dppa_enabled: "true",
  strike_price_vnd: "1800",
  k_factor: "1.02",
  connection_voltage_kv: "22",
  kpp_22: "1.027263",
  kpp_110: "1.008525",
  tariff_off_peak: "45.7692307692308",
  tariff_standard: "70.5",
  tariff_peak: "130.692307692308",
  exchange_rate_usd_vnd: "26000",
  solar_usd_per_mwp: "450000",
  bess_usd_per_mwh: "200000",
  base_rate: "0.065",
  debt_margin: "0.02",
  tenor_years: "10",
  target_dscr: "1.3",
  project_years: "20",
  financial_close_serial: "46022",
  cod_excel_serial: "46023",
  degradation_json: "",
};
